### ISSUE TITLE
Error "Call to undefined function sexplode()" in embed mode

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [cosmocode/dokuwiki-plugin-diagrams#37]
Using the new embed mode brings the following error message:
```
Error: Call to undefined function sexplode()
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the diagrams plugin.
```
The log file gives out the following details:
```
2023-05-17 13:21:33
Error: Call to undefined function sexplode()
/var/www/html/wiki/lib/plugins/diagrams/syntax/embed.php(27)
#0 /var/www/html/wiki/inc/parser/handler.php(279): syntax_plugin_diagrams_embed->handle('<diagram><svg x...', 5, 27, Object(Doku_Handler))
#1 /var/www/html/wiki/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('<diagram><svg x...', 5, 27, 'diagrams_embed')
#2 /var/www/html/wiki/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('<diagram><svg x...', 5, 27)
#3 /var/www/html/wiki/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '<diagram><svg x...', '_plugin_diagram...', 27, 27)
#4 /var/www/html/wiki/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n\n')
#5 /var/www/html/wiki/inc/parserutils.php(223): dokuwiki\Parsing\Parser->parse('\n====== Spielpl...')
#6 /var/www/html/wiki/inc/Ui/PageView.php(56): p_get_instructions('====== Spielpla...')
#7 /var/www/html/wiki/inc/Action/Preview.php(29): dokuwiki\Ui\PageView->show()
#8 /var/www/html/wiki/inc/template.php(100): dokuwiki\Action\Preview->tplContent()
#9 [internal function]: tpl_content_core('preview')
#10 /var/www/html/wiki/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
#11 /var/www/html/wiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
#12 /var/www/html/wiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'preview', 'tpl_content_cor...')
#13 /var/www/html/wiki/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
#14 /var/www/html/wiki/inc/actions.php(27): include('/var/www/html/w...')
#15 /var/www/html/wiki/doku.php(126): act_dispatch()
#16 {main}
```
Best regards
Juergen

**Comment by splitbrain** [comment]
sexplode was added in Jack Jackrum. I updated the compatibility info.
